from enum import StrEnum


class TaskState(StrEnum):
    CREATED = "CREATED"
    REQUIREMENT_ANALYZING = "REQUIREMENT_ANALYZING"
    PRD_APPROVAL = "PRD_APPROVAL"
    ARCHITECTING = "ARCHITECTING"
    ARCH_APPROVAL = "ARCH_APPROVAL"
    CODING = "CODING"
    REVIEWING = "REVIEWING"
    TESTING = "TESTING"
    DEPENDENCY_APPROVAL = "DEPENDENCY_APPROVAL"
    FINAL_VALIDATION = "FINAL_VALIDATION"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    PAUSED = "PAUSED"
    RETRYING = "RETRYING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class IterationKind(StrEnum):
    BUG_FIX = "BUG_FIX"
    REQUIREMENT_CHANGE = "REQUIREMENT_CHANGE"
    OPTIMIZATION = "OPTIMIZATION"


class ExecutionScope(StrEnum):
    AUTO = "AUTO"
    PLAN_ONLY = "PLAN_ONLY"
    WORK_ONLY = "WORK_ONLY"
    REVIEW_ONLY = "REVIEW_ONLY"
    FULL = "FULL"


class DeliveryPreference(StrEnum):
    ECONOMY = "ECONOMY"
    BALANCED = "BALANCED"
    QUALITY = "QUALITY"


class GovernanceLevel(StrEnum):
    FAST = "FAST"
    STANDARD = "STANDARD"
    STRICT = "STRICT"


class DiagnosisStatus(StrEnum):
    CONFIRMED = "CONFIRMED"
    NOT_CONFIRMED = "NOT_CONFIRMED"
    USAGE_GUIDANCE = "USAGE_GUIDANCE"
    INCONCLUSIVE = "INCONCLUSIVE"


class ArtifactType(StrEnum):
    PRD = "PRD"
    DIAGNOSIS = "DIAGNOSIS"
    UI_DESIGN = "UI_DESIGN"
    ARCHITECTURE = "ARCHITECTURE"
    CODE_CHANGE = "CODE_CHANGE"
    REVIEW = "REVIEW"
    TEST_REPORT = "TEST_REPORT"
    VISUAL_REPORT = "VISUAL_REPORT"
    GIT_COMMIT = "GIT_COMMIT"


class ApprovalDecision(StrEnum):
    APPROVED = "APPROVED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"


class ToolCallStatus(StrEnum):
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class ReviewVerdict(StrEnum):
    APPROVED = "APPROVED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"


class ReviewSeverity(StrEnum):
    BLOCKER = "BLOCKER"
    MAJOR = "MAJOR"
    MINOR = "MINOR"
    NIT = "NIT"


class TestRunner(StrEnum):
    NODE_CHECK = "NODE_CHECK"
    STATIC_PAGE_CHECK = "STATIC_PAGE_CHECK"
    PYTHON_COMPILE = "PYTHON_COMPILE"
    PYTEST = "PYTEST"
    UNITTEST = "UNITTEST"
    NPM_TEST = "NPM_TEST"
    NPM_BUILD = "NPM_BUILD"
    MAVEN_TEST = "MAVEN_TEST"


class CommandStatus(StrEnum):
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    TIMED_OUT = "TIMED_OUT"
    ENVIRONMENT_ERROR = "ENVIRONMENT_ERROR"


class TestVerdict(StrEnum):
    PASSED = "PASSED"
    FAILED = "FAILED"
    ENVIRONMENT_ERROR = "ENVIRONMENT_ERROR"


class MemoryType(StrEnum):
    SHORT_TERM = "SHORT_TERM"
    PROJECT = "PROJECT"
    LONG_TERM = "LONG_TERM"


class MemoryStatus(StrEnum):
    CANDIDATE = "CANDIDATE"
    VERIFIED = "VERIFIED"
    STALE = "STALE"
    REJECTED = "REJECTED"


class ExecutionAction(StrEnum):
    START = "START"
    DECIDE_PRD = "DECIDE_PRD"
    DECIDE_ARCHITECTURE = "DECIDE_ARCHITECTURE"
    RUN_REVIEW = "RUN_REVIEW"
    RUN_TESTS = "RUN_TESTS"


class ExecutionStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
