"""initial_schema

Revision ID: 1e5ea4895c29
Revises: 
Create Date: 2026-07-21 17:36:15.897860
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1e5ea4895c29'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('root_path', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('code_chunks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=40), nullable=False),
    sa.Column('symbol_name', sa.Text(), nullable=True),
    sa.Column('symbol_type', sa.String(length=40), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'file_path', 'chunk_index', name='uq_code_chunk_position')
    )
    op.create_index(op.f('ix_code_chunks_file_path'), 'code_chunks', ['file_path'], unique=False)
    op.create_index(op.f('ix_code_chunks_language'), 'code_chunks', ['language'], unique=False)
    op.create_index(op.f('ix_code_chunks_project_id'), 'code_chunks', ['project_id'], unique=False)
    op.create_table('indexed_files',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=40), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'file_path')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('requirement', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('state_version', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'type', 'version', name='uq_artifact_version')
    )
    op.create_index(op.f('ix_artifacts_task_id'), 'artifacts', ['task_id'], unique=False)
    op.create_table('checkpoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('state_version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkpoints_task_id'), 'checkpoints', ['task_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_task_id'), 'events', ['task_id'], unique=False)
    op.create_table('executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('active_task_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('result_state', sa.String(length=40), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['active_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('active_task_id')
    )
    op.create_index(op.f('ix_executions_status'), 'executions', ['status'], unique=False)
    op.create_index(op.f('ix_executions_task_id'), 'executions', ['task_id'], unique=False)
    op.create_table('memories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=80), nullable=False),
    sa.Column('source_id', sa.String(length=120), nullable=True),
    sa.Column('source_revision', sa.String(length=120), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'fingerprint', name='uq_project_memory_fingerprint')
    )
    op.create_index(op.f('ix_memories_category'), 'memories', ['category'], unique=False)
    op.create_index(op.f('ix_memories_project_id'), 'memories', ['project_id'], unique=False)
    op.create_index(op.f('ix_memories_status'), 'memories', ['status'], unique=False)
    op.create_index(op.f('ix_memories_task_id'), 'memories', ['task_id'], unique=False)
    op.create_index(op.f('ix_memories_type'), 'memories', ['type'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('agent_name', sa.String(length=80), nullable=False),
    sa.Column('tool_name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input', sa.JSON(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_calls_task_id'), 'tool_calls', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_calls_task_id'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('ix_memories_type'), table_name='memories')
    op.drop_index(op.f('ix_memories_task_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_status'), table_name='memories')
    op.drop_index(op.f('ix_memories_project_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_category'), table_name='memories')
    op.drop_table('memories')
    op.drop_index(op.f('ix_executions_task_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_status'), table_name='executions')
    op.drop_table('executions')
    op.drop_index(op.f('ix_events_task_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_checkpoints_task_id'), table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_index(op.f('ix_artifacts_task_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('indexed_files')
    op.drop_index(op.f('ix_code_chunks_project_id'), table_name='code_chunks')
    op.drop_index(op.f('ix_code_chunks_language'), table_name='code_chunks')
    op.drop_index(op.f('ix_code_chunks_file_path'), table_name='code_chunks')
    op.drop_table('code_chunks')
    op.drop_table('projects')
    # ### end Alembic commands ###
